name: Create Dev Cluster

on:
  workflow_call:
    inputs:
      cluster-name:
        required: true
        type: string
      flavor:
        required: true
        type: string
      args:
        required: false
        type: string
        default: ''
    outputs:
      cluster-name:
        description: "Name of the created cluster"
        value: ${{ jobs.create-dev-cluster.outputs.cluster-name }}

jobs:
  create-dev-cluster:
    runs-on: ubuntu-latest
    outputs:
      cluster-name: ${{ inputs.cluster-name }}
    steps:
      - uses: stackrox/actions/infra/create-cluster@v1
        with:
          flavor: ${{ inputs.flavor }}
          name: ${{ inputs.cluster-name }}
          args: ${{ inputs.args }}
          lifespan: "2h"
          wait: true
          token: ${{ secrets.INFRA_CI_TOKEN }}
