name: Delete Dev Cluster

on:
  workflow_call:
    inputs:
      cluster-name:
        required: true
        type: string

jobs:
  delete-dev-cluster:
    runs-on: ubuntu-latest
    env:
      INFRA_TOKEN: ${{ secrets.INFRA_CI_TOKEN }}
    steps:
      - name: Install infractl
        uses: stackrox/actions/infra/install-infractl@v1

      - name: Delete cluster
        run: |
          /github/home/.local/bin/infractl delete "${{ inputs.cluster-name }}"
