name: Main

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml

  create-dev-cluster:
    uses: ./.github/workflows/create-dev-cluster.yml
    with:
      cluster-name: infra-roxie-main-${{ github.run_number }}-gke
      flavor: gke-default
      args: machine-type=e2-standard-4,nodes=3,gcp-image-type=ubuntu_containerd
    secrets: inherit

  build-roxie-image:
    uses: ./.github/workflows/build-roxie-image.yml
    permissions:
      contents: read
      packages: write
    secrets: inherit

  e2e-tests:
    needs: [ create-dev-cluster, build-roxie-image ]
    uses: ./.github/workflows/e2e-tests.yml
    with:
      cluster-name: ${{ needs.create-dev-cluster.outputs.cluster-name }}
      image: ${{ needs.build-roxie-image.outputs.image }}
    secrets: inherit

  e2e-tests-kind:
    needs: [ build-roxie-image ]
    uses: ./.github/workflows/e2e-tests-kind.yml
    with:
      image: ${{ needs.build-roxie-image.outputs.image }}
    secrets: inherit

  delete-dev-cluster:
    if: ${{ always() && needs.create-dev-cluster.result == 'success' }}
    needs: [ create-dev-cluster, e2e-tests ]
    uses: ./.github/workflows/delete-dev-cluster.yml
    with:
      cluster-name: ${{ needs.create-dev-cluster.outputs.cluster-name }}
    secrets: inherit
